apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: dotnet
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      nodeSelector:
        kubernetes.io/os: windows
        agentpool: wpool
      containers:
      - name: myapp
        image: samplerndacr.azurecr.io/myapp:$tag_version
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dotnet
  labels:
    app: myapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myapp