apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: mylocalstorage
  resources:
    requests:
      storage: 3Gi
---
# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pvstorage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mssqldb/"
    type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deployment
  namespace: dotnet
  labels:
    app: mydb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: lnpool
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
        volumeMounts:
        - mountPath: "/var/opt/mssql"
          name: mssql-storage
      containers:
      - name: mydb
        image: samplerndacr.azurecr.io/mydb:v1
        ports:
        - containerPort: 1433
        volumeMounts:
          - name: mssql-storage
            mountPath: /var/opt/mssql/data
        env:
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "Basha@123"
      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mydb-service
  namespace: dotnet
  labels:
    app: mydb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  selector:
    app: mydb