name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and push console
      working-directory: .
      run: |
        docker build -t myapp:${{env.version}} --file Dockerfile .
        docker tag myapp:$version samplerndacr.azurecr.io/myapp:$version
        docker login samplerndacr.azurecr.io -u $username -p $password
        docker image push samplerndacr.azurecr.io/myapp:$version
        docker logout
      env:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        version: v8
