
name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-n-push:
    runs-on: windows-2019
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build and push console
      working-directory: .
      shell: bash
      run: |
        export tag_version="$(cat VERSION)";
        docker build -t myapp:$tag_version --file Dockerfile .
        docker tag myapp:$tag_version samplerndacr.azurecr.io/myapp:$tag_version
        docker login samplerndacr.azurecr.io -u ${{env.username}} -p ${{env.password}}
        docker image push samplerndacr.azurecr.io/myapp:$tag_version
        docker logout
      env:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
