
export vers="$(cat VERSION)";name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get version number
      run: |
        export vers="$(cat VERSION)";
        echo "$vers"
      shell: bash

    - name: Set tag var
      id: vars
      run: |
        export vers="$(cat VERSION)";
        echo "docker_tag=$vers" >> $GITHUB_OUTPUT
        echo $docker_tag
      
    - name: Build and push console
      working-directory: .
      run: |
        docker build -t myapp:${{steps.vars.outputs.docker_tag}} --file Dockerfile .
        docker tag myapp:${{env.version}} samplerndacr.azurecr.io/myapp:${{env.version}}
        docker login samplerndacr.azurecr.io -u ${{env.username}} -p ${{env.password}}
        docker image push samplerndacr.azurecr.io/myapp:${{env.version}}
        docker logout
      env:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
