name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and push console
      working-directory: .
      run: |
        docker build . --file Dockerfile --tag myapp:${{ env.REPO_VERSION }}
        docker tag myapp:${{ env.REPO_VERSION }} samplerndacr.azurecr.io/myapp:${{ env.REPO_VERSION }}
        docker login samplerndacr.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker image push samplerndacr.azurecr.io/myapp:${{ env.REPO_VERSION }}
        docker logout
