name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and push console
      working-directory: .
      run: |
        docker build -t myapp:v7 --file Dockerfile .
        docker tag myapp:v7 samplerndacr.azurecr.io/myapp:v7
        docker login samplerndacr.azurecr.io -u $env:username -p $env:password
        docker image push samplerndacr.azurecr.io/myapp:v7
        docker logout
      env:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
